# Generated by Django 4.0 on 2023-10-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0035_auto_20230822_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('field1', models.CharField(default='', max_length=64)),
                ('field_date', models.DateField(default=None, null=True)),
                ('field_datetime', models.DateTimeField(default=None, null=True)),
                ('field_time', models.TimeField(default=None, null=True)),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
